language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g karma-cli
env:
  global:
    - secure: WNnYBuPALK3vtnZ3YHNm1GfMjCjSh+6k5vGpQI3qanKRAH2NesQWKAr73hcRcjVCZgZgyrRdZLqFWqKm/qH5huHFbBg5tDYrvMD2IZMKis0qw0JsuKHre8XEh2/aXxaVSVlRkGt+Se5dautTlVrIXTurm7Fq4E5R3kNwEovEMW0=
    - secure: Fd4qoO1xymW3/gKFSddCstm12Y/4zVewSelBgPHhF+a0X8gfPJY8USHcU+8nIpzBIoB97HHmIttpfMcH0W+AlzXILLH+RYzfLSFxGdfpt2ZUTQLN0sQ8Zueyg3gQAYhhwVpeOhLxEl0X919MhLF3z2dSuCe4v288Okqq5auz+mA=

addons:
  sauce_connect: true
